samples/Samples/Server/NerdDinner/BrightstarDB.Samples.NerdDinner/Controllers/SparqlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BrightstarDB.Client;

namespace BrightstarDB.Samples.NerdDinner.Controllers
{
    public class SparqlController : Controller
    {
        //
        // GET: /Sparql/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(string query)
        {
            if (String.IsNullOrEmpty(query))
            {
                return View("Error");
            }
            var client = BrightstarService.GetClient();
            var results = client.ExecuteQuery("NerdDinner", query);
            return new FileStreamResult(results, "application/xml; charset=utf-8");
        }

    }
}

samples/Samples/Server/NerdDinner/BrightstarDB.Samples.NerdDinner/Views/Shared/404.cshtml
<h2>404 Not Found</h2>

<p>The item could not be found.</p>

samples/Samples/Server/NerdDinner/BrightstarDB.Samples.NerdDinner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
<div class="page">
        <div id="header">
            <div id="title">
                <h1>BrightstarDB Nerd Dinner</h1>
            </div>
            <div id="logindisplay">@Html.Partial("_LogOnPartial")</div>
                @if (ViewData.ContainsKey("OdataLink"))
                {
                    <div class="odatalink">
                    <a href="@ViewData["OdataLink"]"><img width=16 height=16 src="/content/odata.png" alt="OData for this page" title="OData for this page"/></a>
                    </div>
                }
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Query SPARQL", "Index", "Sparql")</li>
                    <li>@Html.ActionLink("Editors Only", "SecureEditorSection", "Home")</li>
                    <li>@Html.ActionLink("Admin Only", "SecureAdminSection", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div></body>
</html>

samples/Samples/Server/NerdDinner/BrightstarDB.Samples.NerdDinner/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}